# Generated by Django 5.1.15 on 2026-03-08 22:05

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='QueryResult',
            fields=[
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('query_text', models.TextField()),
                ('mode', models.CharField(choices=[('plain', 'Plain'), ('graph', 'Graph'), ('compare', 'Compare')], max_length=10)),
                ('llm_provider', models.CharField(max_length=50)),
                ('llm_model', models.CharField(max_length=100)),
                ('graph_tool', models.CharField(blank=True, default='', max_length=50)),
                ('results', models.JSONField(default=dict)),
                ('total_latency_ms', models.FloatField(default=0.0)),
                ('token_count', models.JSONField(default=dict)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='queries', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'query result',
                'verbose_name_plural': 'query results',
                'db_table': 'retrieval_queryresult',
                'ordering': ['-created_at'],
            },
        ),
    ]
