# Generated by Django 5.1.15 on 2026-03-09 18:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("documents", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="document",
            name="blob_download_url",
            field=models.URLField(blank=True, default="", max_length=2048),
        ),
        migrations.AddField(
            model_name="document",
            name="blob_pathname",
            field=models.CharField(blank=True, default="", max_length=1024),
        ),
        migrations.AddField(
            model_name="document",
            name="blob_url",
            field=models.URLField(blank=True, default="", max_length=2048),
        ),
    ]
