# Generated by Django 5.1.15 on 2026-03-08 22:05

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('documents', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='GraphBuildJob',
            fields=[
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('celery_task_id', models.CharField(blank=True, max_length=255, null=True)),
                ('status', models.CharField(choices=[('pending', 'Pending'), ('extracting', 'Extracting'), ('building', 'Building'), ('completed', 'Completed'), ('failed', 'Failed')], default='pending', max_length=20)),
                ('entities_extracted', models.IntegerField(default=0)),
                ('relations_extracted', models.IntegerField(default=0)),
                ('entities_created', models.IntegerField(default=0)),
                ('relations_created', models.IntegerField(default=0)),
                ('error_message', models.TextField(blank=True, default='')),
                ('started_at', models.DateTimeField(blank=True, null=True)),
                ('completed_at', models.DateTimeField(blank=True, null=True)),
                ('document', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='graph_jobs', to='documents.document')),
            ],
            options={
                'verbose_name': 'Graph Build Job',
                'verbose_name_plural': 'Graph Build Jobs',
                'db_table': 'knowledge_graph_graphbuildjob',
                'ordering': ['-created_at'],
            },
        ),
    ]
